# Generated by Django 3.2 on 2022-11-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='location',
            field=models.CharField(default='', max_length=80),
        ),
    ]
