# Generated by Django 3.2 on 2022-11-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='evidence_pic'),
        ),
    ]
