# Generated by Django 3.2 on 2022-11-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='body',
            new_name='Description',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='location',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='photo',
        ),
        migrations.AddField(
            model_name='contact',
            name='County',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='Eircode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='Scale',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=1),
        ),
        migrations.AddField(
            model_name='contact',
            name='Town',
            field=models.CharField(default='', max_length=50),
        ),
    ]
