# Generated by Django 3.2 on 2022-11-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contact_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Scale',
        ),
    ]
