# Generated by Django 3.2 on 2022-11-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_contact_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='scale',
        ),
        migrations.AddField(
            model_name='contact',
            name='Condition',
            field=models.IntegerField(choices=[(1, 'poor condition'), (2, 'Thin'), (3, 'Moderate'), (4, 'Fleshy'), (5, 'Fat')], default=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Description',
            field=models.TextField(default='Please describe the welfare case here & select the condition of the horse below', max_length=100),
        ),
    ]
