# Generated by Django 3.2 on 2022-11-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20221103_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Description',
            field=models.TextField(default='Please describe the welfare case here & select the condition of the horse below:', max_length=500),
        ),
    ]
