# Generated by Django 3.2 on 2022-11-25 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20221125_2140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
